[package]
authors = ["Steven Ferrer <steven.r.ferrer@gmail.com>"]
description = "Rust examples"
edition = "2021"
name = "rust-examples"
version = "0.1.0"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
